# This is a basic workflow to help you get started with Actions

name: Debug

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]


#    types: [ "created" ]

#  deployment_status:
#    types: [ "failure" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tier:
        type: string
        required: true
        description: 'Tier of the deployment'
      org:
        type: string
        required: true
        description: 'Organization of the deployment'
      unit:
        type: string
        required: false
        default: ""
        description: 'Unit of the deployment'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

#      - env:
#          MESSAGE: ${{ fromJSON('["${{ inputs.org }}","${{ inputs.unit }}","${{ inputs.tier }}"]') }}
#        run: echo $MESSAGE | jq .
#        name: fromJSON
      - env:
          MESSAGE: ${{ format('{0}-{1}-{2}', inputs.org, inputs.unit, inputs.tier) }}
        run: echo $MESSAGE
        if: contains(format('{0}-{1}-{2}', inputs.org, inputs.unit, inputs.tier), '--')
        name: join

#      - env:
#          MESSAGE: ${{ join(fromJSON('["${{ inputs.org }}","${{ inputs.unit }}","${{ inputs.tier }}"]'), '-') }}
#        run: echo $MESSAGE
