# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      draft:
        default: "false"
        description: 'Create a draft instead of a release'
        required: false
        options:
          - "false"
          - "true"

          # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it


      - name: Checkout
        uses: actions/checkout@v3

      - name: set date
        id: date
        run: echo "value=$(date +%Y%m%d_%H%M%S)" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          echo ${{ steps.date.outputs.value }} > Release.txt
          echo ${{ steps.date.outputs.value }} > FILE2

      - name: Release
        uses: softprops/action-gh-release@v1

        with:
          body: |
            ## Changes
            - First release
          name: Release name ${{ steps.date.outputs.value }}
          draft: ${{ github.event.inputs.draft }}
          files: |
            Release.txt
            FILE2
