name: service-two - deploy - dev

on:
  workflow_dispatch:

env:
  SERVICE_NAME: service-two
  TIER: int
  ORG: bci

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo "SERVICE_NAME=${SERVICE_NAME}"
            echo "TIER=${TIER}"
            echo "ORG=${ORG}"
            echo "GITHUB_SHA=${GITHUB_SHA}"
