name: service-one - deploy - dev

on:
  workflow_dispatch:

env:
  SERVICE_NAME: service-one
  TIER: dev
  ORG: bci

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: deploy service via pulumi
        uses: ./.github/actions/trigger-deployment-pulumi-utils
        with:
          app: ${{ env.SERVICE_NAME }}
          deploy_commit: ${{ github.ref }}
          tier: ${{ env.TIER }}
          github-token: ${{ secrets.GH_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
