name: Trigger Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - abc-dev
          - abc-int
        required: true
        description: environment to deploy to
      app:
        type: choice
        options:
          - service-one
          - service-two
        required: true
        description: app to be deployed
#
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # output env and tier
      - name: split env and tier
        run: |
            echo "value=$(echo ${{ github.event.inputs.environment }} | cut -d'-' -f1)" >> $GITHUB_OUTPUT
            echo "value=$(echo ${{ github.event.inputs.environment }} | cut -d'-' -f2)" >> $GITHUB_OUTPUT

      - name: trigger deploy of ${{ github.event.inputs.app }} from ${{ github.ref }} to ${{ github.event.inputs.environment }}
        uses: ./.github/actions/deploy-app
        with:
          app: ${{ github.event.inputs.app }}
          ref: ${{ github.ref }}
          tier: ${{ github.event.inputs.environment }}
          github-token: ${{ secrets.GH_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
