name: Trigger Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - abcd
          - efgh
        required: true
        description: environment to deploy to
      app:
        type: choice
        options:
          - service-one
          - service-two

        required: true
        description: app to be deployed

jobs:
  deploy:
    name: deploying ${{ inputs.app }} to ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    secrets: inherit
#    uses: "./.github/workflows/${{ inputs.app }}.yml"
    uses: "./.github/workflows/${{ github.event.inputs.app }}.yml"
# bluecodecom/pulumi-utils/.github/actions/assume-bci-gate@master
